spring.application.name=paysecure-j

spring.datasource.url=jdbc:mysql://localhost:3306/paysecure?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=paysecure_admin
spring.datasource.password=Admin@123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

server.port=8080
